title: <p align="center"> Bijay Mishra </p>
logo: /assets/img/log.jpg

description:
  <p align="center">
  <a href="#">Resume</a> |
  <a href="https://www.linkedin.com/in/sajan-kedia-b06a6821/">LinkedIn</a> |
  <a href="https://github.com/bmishr">GitHub</a>
  
  <br>   
 I am workin as we webdesigner.
  <br>
  </p>



theme: jekyll-theme-minimal
